# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformDocsRecursive < Formula
  desc "Generate Terraform Docs for all Terraform Modules in a Directory"
  homepage "https://github.com/juftin/terraform-docs-recursive"
  version "1.6.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/juftin/terraform-docs-recursive/releases/download/v1.6.0/terraform-docs-recursive_Darwin_x86_64.tar.gz"
      sha256 "e68e02855e1fc2ccab88e371c74b921ba7e5ec9c85760630148868d614b1f365"

      def install
        bin.install "terraform-docs-recursive"
      end
    end
    on_arm do
      url "https://github.com/juftin/terraform-docs-recursive/releases/download/v1.6.0/terraform-docs-recursive_Darwin_arm64.tar.gz"
      sha256 "32c6695cfb73cc3ba8ebfd93a30a9a9705e758ad648fae77bc623ed2078a3840"

      def install
        bin.install "terraform-docs-recursive"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juftin/terraform-docs-recursive/releases/download/v1.6.0/terraform-docs-recursive_Linux_x86_64.tar.gz"
        sha256 "ec5c0a1a453254f4c24e95f66caf15f98ae751169952b828a64e798e3835d544"

        def install
          bin.install "terraform-docs-recursive"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juftin/terraform-docs-recursive/releases/download/v1.6.0/terraform-docs-recursive_Linux_arm64.tar.gz"
        sha256 "9a5155434c6c635d194c409f3c51994c5f8f6e98460f2898e3aab01d89dc8e57"

        def install
          bin.install "terraform-docs-recursive"
        end
      end
    end
  end
end
