# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformDocsRecursive < Formula
  desc "Generate Terraform Docs for all Terraform Modules in a Directory"
  homepage "https://github.com/juftin/terraform-docs-recursive"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/juftin/terraform-docs-recursive/releases/download/v1.0.0/terraform-docs-recursive_Darwin_x86_64.tar.gz"
      sha256 "9324582743a0b703b8b6963dab540313c7aaea83340bc6b8841eed95ef2c8d07"

      def install
        bin.install "terraform-docs-recursive"
      end
    end
    on_arm do
      url "https://github.com/juftin/terraform-docs-recursive/releases/download/v1.0.0/terraform-docs-recursive_Darwin_arm64.tar.gz"
      sha256 "d38d54b84222dc7b926aa9e22b0e4c34bc41fa050856fd40c366b9b4625a49cb"

      def install
        bin.install "terraform-docs-recursive"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juftin/terraform-docs-recursive/releases/download/v1.0.0/terraform-docs-recursive_Linux_x86_64.tar.gz"
        sha256 "3d04c28069ba2d43b7ac2086104ab4a63352f74b58c09be2d9c60a4b4e2c53cc"

        def install
          bin.install "terraform-docs-recursive"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juftin/terraform-docs-recursive/releases/download/v1.0.0/terraform-docs-recursive_Linux_arm64.tar.gz"
        sha256 "731e2677bedbcf026a26bad59097e6b242bfdd5fb56faface04241101735bc2d"

        def install
          bin.install "terraform-docs-recursive"
        end
      end
    end
  end
end
