# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release
on:
    push:
        branches:
            - main
            - next
            - beta
            - alpha
            - "*.x"
jobs:
    release:
        name: github-release
        if: github.repository_owner == 'juftin'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ env.GOVERSION || '1.23' }}
            - name: Install goreleaser
              run: |
                  go install github.com/goreleaser/goreleaser/v2@latest
                  goreleaser --version
            - name: Semantic Release
              uses: juftin/actions/semantic-release@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
